package:
  name: stisblazefix
  version: 1.2

source:
  path: .

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy >=1.13
    - scipy
    - astropy
    - matplotlib

about:
  #home: http://stisblazefix.readthedocs.io
  license: BSD-new
  license_file: LICENSE.txt
  summary: HST/STIS echelle blaze function correction

extra:
  maintainer: Charles Proffitt
  maintainer_email: help@stsci.edu
