name: Publish Python Package

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    if: ${{ !github.event.release.prerelease }}
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine setuptools-scm

      - name: Show version
        run: python -c "import setuptools_scm; print(setuptools_scm.get_version())"

      - name: Build package
        run: python -m build --no-isolation

      - name: Check distribution metadata
        run: twine check dist/*

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc  # v1.12.4
